


right_format = """ 
$time\
$battery\
$shlvl\
"""


format = """

$username\
$container\
$directory\
$cmd_duration\
$sudo\
$deno\
$golang\
$java\
$zig\
$nodejs\
$hostname\
$git_branch\
$git_commit\
$git_state\
$git_status\
$git_metrics\
$docker_context\
$package\
$lua\
$r\
$perl\
$python\
$os\
$memory_usage\
$line_break\
$jobs\
$status\
$shell\
$character\

"""


[git_commit]
disabled = false
commit_hash_length = 4
tag_symbol = 'ğŸ”– '


[git_status]
style = 'bold cyan'
format = '([$all_status$ahead_behind]($style) )'
conflicted = 'ğŸ³${count}|'
ahead = 'ğŸš€ ${count}|'
behind = 'ğŸŒ ${count}|'
diverged = 'ğŸ’”'
up_to_date = 'ğŸ˜‡'
untracked = 'ğŸ§ ${count}|'
stashed = 'ğŸ—„ï¸ ${count}|'
modified = 'ğŸ“ ${count}|'
staged = '[++\($count\)](green)'
renamed = 'ğŸ¥¸ ${count}|'
deleted = 'ğŸ—‘ ${count}|'


[shlvl]
disabled = false
symbol = """ğŸš """
threshold = 3
format = """\n[$symbol$shlvl]($style) """


[shell]
disabled = false
fish_indicator = "xsh"

[battery]
disabled = false
full_symbol = 'ğŸ’¯ '
charging_symbol = 'ğŸ”Œ '
discharging_symbol = 'â›« '

[[battery.display]]
threshold = 100
style = 'bold green'


[character]
# error_symbol = '[â—](bold red)'
error_symbol = '[â®¾](bold red)'

[bun]
format = '[$symbol](bold green)'
disabled = false

[cmd_duration]
show_milliseconds = false
format = """\n [$duration]($style) âŒ› \n\n"""
show_notifications = true
min_time_to_notify = 30_000

[container]
symbol = ' ğŸ§'
disabled = true
style = 'bold cyan'
format = '[cros $symbol]($style)'

[zig]
format = '[$symbol($version )]($style)'
symbol = " ğŸŠ"
style = "bold cyan"

[directory]
format = """ [now in $path]($style)[$read_only]($read_only_style) \n"""
home_symbol = "ğŸšï¸"
truncation_length = 1

[directory.substitutions]
'workspace' = 'ğŸ§ª'
'huetiful' = 'ğŸ¨'
'.math' = 'ğŸ§®'
'sources' = 'ğŸ”¬'
'me' = 'ğŸ““'
'cast2gif' = 'ğŸ“º'
'lazyflow' = 'ğŸ¦¥'
'.nvim' = 'ğŸ§‘â€ğŸ’»'
'.lua' = 'ğŸ‘'
[c]
symbol = " ğŸ§®"
format = ' [$symbol $name $version]($style)'

[memory_usage]
threshold = 10


[package]
format = ' [$symbol @$version]($style)'

[nodejs]
format = '[$symbol]($style)'

[sudo]
disabled = true
symbol = '|= su '
format = """[$symbol]($style)\n"""


[time]
disabled = false
format = """ [$time ]($style)\n """
style = 'dim purple'
time_format = "%H|%M"
